delete from contract_item;
delete from contract_category;
delete from order_item;
delete from order_category;
delete from category;
delete from "order";
delete from contract;
delete from item;
delete from institution;

drop table contract_item;
drop table contract_category;
drop table order_item;
drop table order_category;
drop table category;
drop table "order";
drop table contract;
drop table item;
drop table institution;